@GestionSetlistApp_HostAddress = http://localhost:5034

GET {{GestionSetlistApp_HostAddress}}/morceaux
Accept: application/json


### Suppresion de tous les morceaux
DELETE {{GestionSetlistApp_HostAddress}}/morceaux/deleteAll
Accept:  application/json


### Ajout d'un Element
POST {{GestionSetlistApp_HostAddress}}/morceaux
Content-Type: application/json

{
    "Titre" : "Devolution",
    "Artiste" : "Starset"
}


### Ajout de plusieurs Elements
POST {{GestionSetlistApp_HostAddress}}/morceaux/addMany
Content-Type: application/json

[
    {
        "Titre" : "Little Wing",
        "Artiste" : "Jimi Hendrix"
    },
    {
        "Titre" : "Back in Black",
        "Artiste" : "ACDC"
    }
]

### Get Morceau avec Id
GET {{GestionSetlistApp_HostAddress}}/morceaux/2
Accept: application/json

###
GET {{GestionSetlistApp_HostAddress}}/morceaux/testYoutubeApi
Accept: application/json
