@GestionSetlistApp_HostAddress = http://localhost:5034/api/membre

### Get All Membres
GET {{GestionSetlistApp_HostAddress}}
Accept: application/json

### Get Membre
GET {{GestionSetlistApp_HostAddress}}/1
Accept: application/json

### Ajout d'un membre
POST {{GestionSetlistApp_HostAddress}}
Content-Type: application/json

{
    "Nom" : "Lasiek",
    "Prenom" : "Kylian",
    "DateNaissance" : "2001-12-01"
}

### Ajout de InstrumentToMembre
POST {{GestionSetlistApp_HostAddress}}/1/instrument/
Content-Type: application/json

{
    "InstrumentId" : 1
}

### Patch d'un membre
PATCH {{GestionSetlistApp_HostAddress}}/1
Content-Type: application/json

{
    "Nom" : "Lasik"
}

### Patch d'un membre
PATCH {{GestionSetlistApp_HostAddress}}/1
Content-Type: application/json

{
    "Prenom" : "Kylian"
}

### Patch d'un membre
PATCH {{GestionSetlistApp_HostAddress}}/1
Content-Type: application/json

{
    "DateNaissance" : "2001-07-01"
}

### Delete Membre
DELETE {{GestionSetlistApp_HostAddress}}/1
Accept: application/json


### Delete Membre
DELETE {{GestionSetlistApp_HostAddress}}/1/instrument/1
Accept: application/json