@GestionSetlistApp_HostAddress = http://localhost:5034/api/membre

### Get All Membres
GET {{GestionSetlistApp_HostAddress}}
Accept: application/json

### Get Membre
GET {{GestionSetlistApp_HostAddress}}/2
Accept: application/json

### Delete Membre
DELETE {{GestionSetlistApp_HostAddress}}/7
Accept: application/json

### Delete All Membres
DELETE {{GestionSetlistApp_HostAddress}}
Accept: application/json

### Ajout d'un membre
POST {{GestionSetlistApp_HostAddress}}
Content-Type: application/json

{
    "Nom" : "OUI",
    "Prenom" : "Angéline",
    "DateNaissance" : "2001-11-13"
}

### Ajout de membres
POST {{GestionSetlistApp_HostAddress}}/batch
Content-Type: application/json

[
    {
        "Nom" : "Lasik",
        "Prenom" : "Kylian",
        "DateNaissance" : "2001-07-01"
    },
    {
        "Nom" : "Delcros",
        "Prenom" : "Angéline",
        "DateNaissance" : "2001-11-13"
    },
    {
        "Nom" : "Doe",
        "Prenom" : "John",
        "DateNaissance" : "1987-02-05"
    }
]

### Update d'un membre
PUT {{GestionSetlistApp_HostAddress}}/2
Content-Type: application/json

{
    "Nom" : "Lasik",
    "Prenom" : "Kylian",
    "DateNaissance" : "2001-07-01"
}

### Patch d'un membre
PATCH {{GestionSetlistApp_HostAddress}}/1
Content-Type: application/json

{
    "Nom" : "Delcros"
}

