@GestionSetlistApp_HostAddress = http://localhost:5034/api/evenement

### Get All Evenement
GET {{GestionSetlistApp_HostAddress}}
Accept: application/json

### Get Evenement
GET {{GestionSetlistApp_HostAddress}}/1
Accept: application/json


### Add Evenement
POST {{GestionSetlistApp_HostAddress}}
Content-Type: application/json

{
    "Nom" : "Hellfest",
    "Date" : "2025-05-01",
    "Lieu" : "Inconnu"
}

### Patch Evenement (ajout d'une setlist)
PATCH {{GestionSetlistApp_HostAddress}}/1
Content-Type: application/json

{
    "Lieu" : "Marseille",
    "SetlistId" : 1
}

### Delete Evenement
DELETE {{GestionSetlistApp_HostAddress}}/1
Accept: application/json