@GestionSetlistApp_HostAddress = http://localhost:5034

GET {{GestionSetlistApp_HostAddress}}/morceau
Accept: application/json


### Suppresion de tous les morceaux
DELETE {{GestionSetlistApp_HostAddress}}/morceau/deleteAll
Accept:  application/json

### Suppresion d'un morceau
DELETE {{GestionSetlistApp_HostAddress}}/morceau/3
Accept:  application/json

### Ajout d'un Element
POST {{GestionSetlistApp_HostAddress}}/morceau
Content-Type: application/json

{
    "Titre" : "Devolution",
    "Artiste" : "Starset"
}


### Ajout de plusieurs Elements
POST {{GestionSetlistApp_HostAddress}}/morceau/batch
Content-Type: application/json

[
    {
        "Titre" : "Little Wing",
        "Artiste" : "Jimi Hendrix"
    },
    {
        "Titre" : "Back in Black",
        "Artiste" : "ACDC"
    }
]

### Get Morceau avec Id
GET {{GestionSetlistApp_HostAddress}}/morceau/2
Accept: application/json

###
GET {{GestionSetlistApp_HostAddress}}/morceau/testYoutubeApi
Accept: application/json
